/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SaldosRouteImport } from './routes/saldos'
import { Route as PixRouteImport } from './routes/pix'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DiagnosticoMetaRouteImport } from './routes/diagnostico-meta'
import { Route as AgenteRouteImport } from './routes/agente'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ClientsIndexRouteImport } from './routes/clients.index'
import { Route as ClientsIdRouteImport } from './routes/clients.$id'
import { Route as CampaignsNewRouteImport } from './routes/campaigns.new'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as CampaignsEditIdRouteImport } from './routes/campaigns.edit.$id'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth.google.callback'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SaldosRoute = SaldosRouteImport.update({
  id: '/saldos',
  path: '/saldos',
  getParentRoute: () => rootRouteImport,
} as any)
const PixRoute = PixRouteImport.update({
  id: '/pix',
  path: '/pix',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DiagnosticoMetaRoute = DiagnosticoMetaRouteImport.update({
  id: '/diagnostico-meta',
  path: '/diagnostico-meta',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenteRoute = AgenteRouteImport.update({
  id: '/agente',
  path: '/agente',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIndexRoute = ClientsIndexRouteImport.update({
  id: '/clients/',
  path: '/clients/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientsIdRoute = ClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsNewRoute = CampaignsNewRouteImport.update({
  id: '/campaigns/new',
  path: '/campaigns/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsEditIdRoute = CampaignsEditIdRouteImport.update({
  id: '/campaigns/edit/$id',
  path: '/campaigns/edit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/agente': typeof AgenteRoute
  '/diagnostico-meta': typeof DiagnosticoMetaRoute
  '/login': typeof LoginRoute
  '/pix': typeof PixRoute
  '/saldos': typeof SaldosRoute
  '/settings': typeof SettingsRoute
  '/tarefas': typeof TarefasRoute
  '/vendas': typeof VendasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/clients/$id': typeof ClientsIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/campaigns/edit/$id': typeof CampaignsEditIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/agente': typeof AgenteRoute
  '/diagnostico-meta': typeof DiagnosticoMetaRoute
  '/login': typeof LoginRoute
  '/pix': typeof PixRoute
  '/saldos': typeof SaldosRoute
  '/settings': typeof SettingsRoute
  '/tarefas': typeof TarefasRoute
  '/vendas': typeof VendasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/clients/$id': typeof ClientsIdRoute
  '/clients': typeof ClientsIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/campaigns/edit/$id': typeof CampaignsEditIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/agente': typeof AgenteRoute
  '/diagnostico-meta': typeof DiagnosticoMetaRoute
  '/login': typeof LoginRoute
  '/pix': typeof PixRoute
  '/saldos': typeof SaldosRoute
  '/settings': typeof SettingsRoute
  '/tarefas': typeof TarefasRoute
  '/vendas': typeof VendasRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/campaigns/new': typeof CampaignsNewRoute
  '/clients/$id': typeof ClientsIdRoute
  '/clients/': typeof ClientsIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
  '/campaigns/edit/$id': typeof CampaignsEditIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agenda'
    | '/agente'
    | '/diagnostico-meta'
    | '/login'
    | '/pix'
    | '/saldos'
    | '/settings'
    | '/tarefas'
    | '/vendas'
    | '/auth/callback'
    | '/campaigns/new'
    | '/clients/$id'
    | '/clients/'
    | '/auth/google/callback'
    | '/campaigns/edit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/agente'
    | '/diagnostico-meta'
    | '/login'
    | '/pix'
    | '/saldos'
    | '/settings'
    | '/tarefas'
    | '/vendas'
    | '/auth/callback'
    | '/campaigns/new'
    | '/clients/$id'
    | '/clients'
    | '/auth/google/callback'
    | '/campaigns/edit/$id'
  id:
    | '__root__'
    | '/'
    | '/agenda'
    | '/agente'
    | '/diagnostico-meta'
    | '/login'
    | '/pix'
    | '/saldos'
    | '/settings'
    | '/tarefas'
    | '/vendas'
    | '/auth/callback'
    | '/campaigns/new'
    | '/clients/$id'
    | '/clients/'
    | '/auth/google/callback'
    | '/campaigns/edit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgendaRoute: typeof AgendaRoute
  AgenteRoute: typeof AgenteRoute
  DiagnosticoMetaRoute: typeof DiagnosticoMetaRoute
  LoginRoute: typeof LoginRoute
  PixRoute: typeof PixRoute
  SaldosRoute: typeof SaldosRoute
  SettingsRoute: typeof SettingsRoute
  TarefasRoute: typeof TarefasRoute
  VendasRoute: typeof VendasRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CampaignsNewRoute: typeof CampaignsNewRoute
  ClientsIdRoute: typeof ClientsIdRoute
  ClientsIndexRoute: typeof ClientsIndexRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
  CampaignsEditIdRoute: typeof CampaignsEditIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saldos': {
      id: '/saldos'
      path: '/saldos'
      fullPath: '/saldos'
      preLoaderRoute: typeof SaldosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pix': {
      id: '/pix'
      path: '/pix'
      fullPath: '/pix'
      preLoaderRoute: typeof PixRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diagnostico-meta': {
      id: '/diagnostico-meta'
      path: '/diagnostico-meta'
      fullPath: '/diagnostico-meta'
      preLoaderRoute: typeof DiagnosticoMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agente': {
      id: '/agente'
      path: '/agente'
      fullPath: '/agente'
      preLoaderRoute: typeof AgenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/': {
      id: '/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof ClientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clients/$id': {
      id: '/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof ClientsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/new': {
      id: '/campaigns/new'
      path: '/campaigns/new'
      fullPath: '/campaigns/new'
      preLoaderRoute: typeof CampaignsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/edit/$id': {
      id: '/campaigns/edit/$id'
      path: '/campaigns/edit/$id'
      fullPath: '/campaigns/edit/$id'
      preLoaderRoute: typeof CampaignsEditIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgendaRoute: AgendaRoute,
  AgenteRoute: AgenteRoute,
  DiagnosticoMetaRoute: DiagnosticoMetaRoute,
  LoginRoute: LoginRoute,
  PixRoute: PixRoute,
  SaldosRoute: SaldosRoute,
  SettingsRoute: SettingsRoute,
  TarefasRoute: TarefasRoute,
  VendasRoute: VendasRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CampaignsNewRoute: CampaignsNewRoute,
  ClientsIdRoute: ClientsIdRoute,
  ClientsIndexRoute: ClientsIndexRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
  CampaignsEditIdRoute: CampaignsEditIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
