// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ysdmtkxhedezijhqlwuc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlzZG10a3hoZWRlemlqaHFsd3VjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzMzMzYyMDgsImV4cCI6MjA4ODkxMjIwOH0.f3rX4qDzPa_K4Y4qB7gOISwK8vHxFUm8BMWN_EVGgNQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});